# services define individual containers and their configurations
services:

  # reverse proxy server
  nginx:
    restart: unless-stopped
    image: nginx:1.24.0
    container_name: nginx_server
    ports:
      - "4000:4000" # ride sharing api http port
      - "5000:5000" # ride sharing customer api http port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/server.crt.pem:/etc/nginx/ssl/nginx.crt.pem # ssl certificate file
      - ~/server.key.pem:/etc/nginx/ssl/nginx.key.pem # ssl certificate key file
    networks:
      - globalnet
    depends_on:
      - keycloak

  # RideSharing API
  ridesharing-api:
    build:
      context: .
      dockerfile: src/RideSharingService/RideSharing.InternalAPI/Dockerfile
    container_name: ridesharing-api
    restart: unless-stopped
    networks:
      - globalnet

  # RideSharing Customer API
  ridesharing-customer-api:
    build:
      context: .
      dockerfile: src/RideSharingService/RideSharing.CustomerAPI/Dockerfile
    container_name: ridesharing-customer-api
    restart: unless-stopped
    networks:
      - globalnet
  

# volumes are a physical areas of disk space shared between the host and the containers
# volumes:


# networks define the communication rules between containers, and between a container and the host
networks:
  keycloak-local: # network for keycloak communication
  globalnet: # network for api communications
