version: '3'
services:
  # distributed cache service
  redis-server:
    image: redis/redis-stack-server:latest
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379" 
    volumes:
      - ~/ridesharing/redis/data:/data
  # GUI for managing redis
  redis-commander: # a Node.js web application that can be used to view, edit and manage your Redis databases
    image: "rediscommander/redis-commander:latest"
    container_name: redis-management-console
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=password
    ports:
      - "8081:8081"
    depends_on:
      - redis
